changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: 🎉 New Features
      labels:
        - "Type: Enhancement"
    - title: 🐞 Bugs Fixes
      labels:
        - "Type: Bug" 
    - title: 🔨 Maintenance
      labels:
        - "Type: Maintenance" 
    - title: Other Changes
      labels:
        - "*"