before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin

  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'

  binary: '{{ .ProjectName }}'
  main: cmd/naabu/main.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256