name: Build
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:          
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test .
        working-directory: cmd/naabu/

      - name: Build
        run: go build .
        working-directory: cmd/naabu/